export default  ACTIONS = {
    SET_CHATS: "SET_CHATS",
    SET_MESSAGES: "SET_MESSAGES",
    ADD_MESSAGE: "ADD_MESSAGE",
    DELETE_MESSAGE: "DELETE_MESSAGE",
    GET_MESSAGES: "GET_MESSAGES",
    SET_AGENT: "SET_AGENT"
    
}