export const Images = {
    background: require('../assets/background.jpg'),
    backgroundGif: require('../assets/backgroundGif.gif'),
    chatlenger: require('../assets/chatlenger.png'),
    facebook: require('../assets/facebook.png'),
    loginBackground: require('../assets/loginBackground.jpg'),
    homeBackground: require('../assets/homeBackground.png'),
    twitter: require('../assets/twitter.png'),
    google: require('../assets/google.png'),
    registerBackground: require('../assets/backgroundRegister.jpg'),
    user1: require('../assets/user1.jpg'),
    user2: require('../assets/user2.jpg'),
    user3: require('../assets/user3.jpg'),
    callbackground: require('../assets/callbackground.jpg'),
    calluser1: require('../assets/calluser1.png'),
    calluser2: require('../assets/calluser2.png'),
    drawerBackground: require('../assets/drawerBackground.jpg'),
    b1: require('../assets/1.png'),
    b2: require('../assets/2.png'),
    b3: require('../assets/3.png'),
    b4: require('../assets/4.png'),
    b5: require('../assets/5.png'),
    b6: require('../assets/6.png'),
    b11: require('../assets/11.png'),
    b22: require('../assets/22.png'),
    b33: require('../assets/33.png'),
    b44: require('../assets/44.png'),
    b55: require('../assets/55.png'),
    b66: require('../assets/66.png'),
    avatarBackgroung: require('../assets/avatarBackground.gif'),
    chatBackground: require('../assets/chatBackground.jpg'),
    mansion1: require('../assets/mansion1.jpg'),
    mansion2: require('../assets/mansion2.jpg'),
    mansion3: require('../assets/mansion3.jpg'),
    house: require('../assets/house.png'),
    land: require('../assets/land.png'),
    empty: require('../assets/empty.jpg'),
    textBackground: require('../assets/textBackground.png'),
    userLocation: require('../assets/userLocation.png'),
    placeLocation: require('../assets/placeLocation.png'),
    logo: require('../assets/IMMO_logo.png'),
    logo1: require('../assets/logoImmo.png'),
    stars: require('../assets/stars.gif'),
    heart: require('../assets/heart.png'),
    
}


